resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/spilth/concourse-maven-spring-boot.git
      branch: master
  - name: schedule
    type: time
    source:
      interval: 300s

jobs:
  - name: package
    plan:
    - aggregate:
      - get: source-code
        trigger: true
      - get: schedule
    - task: package
      privileged: true
      file: source-code/concourse/package.yml
